name: Rewrite âœ…
on:
  push:
    branches:
      - main
      - 'releases/**'
    paths:
      - '.github/**'
  pull_request:
    paths:
      - '.github/**'
permissions: {}
jobs:
  rewrite:
    name: Sanity Check ðŸ•Š
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout Repository ðŸ“¥
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Dry Run ðŸŒ€
        uses: ./.github/actions/run-gradle
        with:
          encryptionKey: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: rewriteDryRun -Dorg.gradle.jvmargs=-Xmx4G